title: "OCI HPC BM Cluster Stack"
description: "Provision a head node and 4 BM.Optimized3.36 nodes on OCI."
informationalText: "Provide one RHEL 8.8 image OCID for BM nodes; the same image is used for the head node. Tenancy and region are pre-filled from your session."
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
  - title: "Target Configuration"
    variables:
      - compartment_ocid
      - ssh_public_key
      - bm_node_image_ocid
      - head_node_image_ocid

  - title: "Networking"
    variables:
      - use_existing_vcn
      - existing_vcn_id
      - existing_public_subnet_id
      - existing_private_subnet_id

  - title: "Ansible from head"
    variables:
      - run_ansible_from_head
      - instance_ssh_user
      - head_node_ssh_user
      - rhsm_username
      - rhsm_password
      - rdma_ping_target

  - title: "Stack context (pre-filled from your session)"
    variables:
      - tenancy_ocid
      - region

variables:
  tenancy_ocid:
    type: string
    title: "Tenancy OCID"
    description: "Pre-filled from your session. Change only if deploying to a different tenancy."
    required: true

  region:
    type: oci:identity:region:name
    title: "Region"
    description: "Pre-filled from your session. Change only if deploying to a different region."
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "Compartment where resources are created."
    required: true
    dependsOn:
      compartmentId: ${tenancy_ocid}

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "SSH Public Key"
    description: "Public key injected into all instances."
    required: true

  bm_node_image_ocid:
    type: oci:core:image:id
    title: "RHEL 8.8 Image (BM nodes)"
    description: "RHEL 8.8 image for BM cluster network nodes."
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

  head_node_image_ocid:
    type: oci:core:image:id
    title: "Head node image (optional)"
    description: "Image for the head node. If empty, uses latest Oracle Linux 8 (recommended; no RHSM on head). Ansible registers RHEL on BM nodes only."
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  use_existing_vcn:
    type: boolean
    title: "Use Existing VCN"
    description: "If true, provide existing VCN and subnet OCIDs below."
    default: false
    required: true

  existing_vcn_id:
    type: oci:core:vcn:id
    title: "Existing VCN"
    description: "Required when Use Existing VCN is true."
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}

  existing_public_subnet_id:
    type: oci:core:subnet:id
    title: "Existing Public Subnet"
    description: "Public subnet for the head node when using existing VCN."
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${existing_vcn_id}

  existing_private_subnet_id:
    type: oci:core:subnet:id
    title: "Existing Private Subnet"
    description: "Private subnet for BM nodes when using existing VCN."
    required: false
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${existing_vcn_id}

  run_ansible_from_head:
    type: boolean
    title: "Run Ansible from head at first boot"
    description: "If true, head node runs RHEL + RDMA Ansible playbook at first boot. Requires head node in a dynamic group with instance principal (see README)."
    default: false
    required: true

  instance_ssh_user:
    type: string
    title: "SSH user for BM nodes"
    description: "Default user on RHEL BM image (e.g. cloud-user). Used for Ansible inventory for BM nodes."
    default: "cloud-user"
    required: false

  head_node_ssh_user:
    type: string
    title: "SSH user for head node (optional)"
    description: "Default user on head node image (e.g. opc for Oracle Linux). If empty, uses SSH user for BM nodes."
    default: ""
    required: false

  rhsm_username:
    type: string
    title: "RHSM username"
    description: "Red Hat Subscription Manager username (when Run Ansible from head is true)."
    required: false

  rhsm_password:
    type: string
    title: "RHSM password"
    description: "Red Hat Subscription Manager password (when Run Ansible from head is true)."
    required: false

  rdma_ping_target:
    type: string
    title: "RDMA ping target IP"
    description: "Optional IP for RDMA ping check (e.g. another BM node's RDMA interface)."
    required: false

outputs:
  created_vcn_id:
    title: "Created/Selected VCN OCID"
    visible: true
  head_node_public_ip:
    title: "Head Node Public IP"
    visible: true
  bm_node_private_ips:
    title: "BM Node Private IPs"
    visible: true
